#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, armEncoder,     sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, PIDControl, driveRight, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Base code for moving forward and turning


const float NORMAL_SPEED = 63;
const float SLOW_SPEED = 40;
const float ROTATIONS_TO_TICKS = 627.2;
const int WHEEL_DIAMETER = 4;
const float WHEEL_CIRCUM = WHEEL_DIAMETER * PI;

void resetEncoders();
void doNothing(int ms);
void forward(float rotations);
void backward(float rotations);
void turnLeft(float rotations);
void turnRight(float rotations);
void closeClaw();
void openClaw();
void moveArmUp(float time);
void moveArmDown(float time);

void resetEncoders()
{
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
}

void doNothing(int ms)
{
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	motor[clawMotor] = 0;
	motor[armMotor] = 0;
	wait1Msec(ms);
}

void forward(float rotations)
{
	resetEncoders();
	while(abs(getMotorEncoder(rightMotor)) < rotations * ROTATIONS_TO_TICKS && abs(getMotorEncoder(leftMotor)) < rotations * ROTATIONS_TO_TICKS)
	{
		if(abs(getMotorEncoder(rightMotor)) < abs(getMotorEncoder(leftMotor))) //if leftMotor has gone farther...
		{
			motor[rightMotor] = NORMAL_SPEED; //run rightMotor at normal speed
			motor[leftMotor] = SLOW_SPEED; //slow down leftMotor
		}
		if(abs(getMotorEncoder(rightMotor)) > abs(getMotorEncoder(leftMotor))) //if rightMotor has gone farther...
		{
			motor[rightMotor] = SLOW_SPEED; //slow down rightMotor
			motor[leftMotor] = NORMAL_SPEED; //run leftMotor at normal speed
		}
		if(abs(getMotorEncoder(rightMotor)) == abs(getMotorEncoder(rightMotor))) //if rightMotor and leftMotor have gone the same distance
		{
			motor[rightMotor] = NORMAL_SPEED; //run rightMotor at normal speed
			motor[leftMotor] = NORMAL_SPEED; //run leftMotor at normal speed
		}
	}
	motor[rightMotor] = 0; //stop motors
	motor[leftMotor] = 0;
}

void backward(float rotations)
{
	resetEncoders();
	while(abs(getMotorEncoder(rightMotor)) < rotations * ROTATIONS_TO_TICKS && abs(getMotorEncoder(leftMotor)) < rotations * ROTATIONS_TO_TICKS)
	{
		if(abs(getMotorEncoder(rightMotor)) < abs(getMotorEncoder(leftMotor))) //if leftMotor has gone farther...
		{
			motor[rightMotor] = -NORMAL_SPEED; //run rightMotor at normal speed
			motor[leftMotor] = -SLOW_SPEED; //slow down leftMotor
		}
		if(abs(getMotorEncoder(rightMotor)) > abs(getMotorEncoder(leftMotor))) //if rightMotor has gone farther...
		{
			motor[rightMotor] = -SLOW_SPEED; //slow down rightMotor
			motor[leftMotor] = -NORMAL_SPEED; //run leftMotor at normal speed
		}
		if(abs(getMotorEncoder(rightMotor)) == abs(getMotorEncoder(rightMotor))) //if rightMotor and leftMotor have gone the same distance
		{
			motor[rightMotor] = -NORMAL_SPEED; //run rightMotor at normal speed
			motor[leftMotor] = -NORMAL_SPEED; //run leftMotor at normal speed
		}
	}
	motor[rightMotor] = 0; //stop motors
	motor[leftMotor] = 0;
}

void turnLeft(float rotations)
{
	resetEncoders();
	while(abs(getMotorEncoder(leftMotor)) < rotations * ROTATIONS_TO_TICKS)
	{
		motor[leftMotor] = -NORMAL_SPEED;
		motor[rightMotor] = NORMAL_SPEED;
	}
	motor[rightMotor] = 0; 
	motor[leftMotor] = 0;
}

void turnRight(float rotations)
{
	resetEncoders();
	while(abs(getMotorEncoder(rightMotor)) < rotations * ROTATIONS_TO_TICKS)
	{
		motor[leftMotor] = NORMAL_SPEED;
		motor[rightMotor] = -NORMAL_SPEED;
	}
	motor[rightMotor]=0;
	motor[leftMotor]=0;
}

void closeClaw()
{
	motor[clawMotor] = -20;
	wait1Msec(1400);
	motor[clawMotor] = 0;
}
void openClaw()
{
	motor[clawMotor] = 40;
	wait1Msec(1400);
	motor[clawMotor] = 0;
}

void moveArmUp(float time)
{
	motor[armMotor] = 40;
	wait1Msec(time);
	motor[armMotor] = 0;
}

void moveArmDown(float time)
{
	motor[armMotor] = -40;
	wait1Msec(time);
	motor[armMotor] = 0;
}

task main()
{
	//ALWAYS START CHALLENGE WITH CLAW OPEN!!!
	forward((2 * 12 - 0.5) / WHEEL_CIRCUM);
	doNothing(1000);
	turnLeft(0.8);
	doNothing(1000);
	forward((2.4 * 12 + 1) / WHEEL_CIRCUM);
	doNothing(1000);
	turnLeft(0.775);
	doNothing(1000);
	forward(13.25 / WHEEL_CIRCUM);
	doNothing(1000);
	closeClaw();
	doNothing(1000);
	moveArmUp(900);
	doNothing(1000);
	turnLeft(1.5);
	doNothing(1000);
	forward((2.7 * 12 + 2.5) / WHEEL_CIRCUM);
	doNothing(1000); 
	turnRight(0.7);
	doNothing(1000);
	moveArmUp(200);
	forward(3.5 / WHEEL_CIRCUM);
	doNothing(1000);
	//moveArmDown(15);
	doNothing(1000);
	openClaw();
	doNothing(1000);
	moveArmUp(300);
	doNothing(1000);
	backward(2 / WHEEL_CIRCUM);
	doNothing(1000);
	moveArmDown(600);
	doNothing(1000);
	forward(2.5 / WHEEL_CIRCUM);
	doNothing(1000);
	closeClaw();
	doNothing(1000);
	moveArmUp(900);
	doNothing(1000);
	turnRight(0.7);
	doNothing(1000);
	forward(1.5 * 12 / WHEEL_CIRCUM);
	doNothing(1000);
	turnLeft(0.7);
	doNothing(1000);
	forward(2 * 12 / WHEEL_CIRCUM);
	doNothing(1000);
	turnLeft(0.7);
	doNothing(1000);
	forward(12 / WHEEL_CIRCUM);
	doNothing(1000);
	moveArmDown(900);
	doNothing(1000);
	openClaw();
}
